[2023-09-20T17:31:35.367+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T17:31:34.535272+00:00 [queued]>
[2023-09-20T17:31:35.375+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T17:31:34.535272+00:00 [queued]>
[2023-09-20T17:31:35.375+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T17:31:35.389+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_dataframe_student> on 2023-09-20 17:31:34.535272+00:00
[2023-09-20T17:31:35.394+0000] {standard_task_runner.py:57} INFO - Started process 1528 to run task
[2023-09-20T17:31:35.397+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'create_dataframe_student', 'manual__2023-09-20T17:31:34.535272+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmp6viilmuz']
[2023-09-20T17:31:35.400+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask create_dataframe_student
[2023-09-20T17:31:35.440+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T17:31:34.535272+00:00 [running]> on host 64864ba3aa5a
[2023-09-20T17:31:35.700+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='create_dataframe_student' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T17:31:34.535272+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T17:31:34.535272+00:00'
[2023-09-20T17:31:35.714+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 21, in create_dataframe
    json_data = xcom_pull_obj[0]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 794, in __getitem__
    raise IndexError(key) from None
IndexError: 0
[2023-09-20T17:31:35.723+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=create_dataframe_student, execution_date=20230920T173134, start_date=20230920T173135, end_date=20230920T173135
[2023-09-20T17:31:35.734+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 65 for task create_dataframe_student (0; 1528)
[2023-09-20T17:31:35.770+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T17:31:35.783+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
