[2023-09-21T00:53:15.589+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T00:53:10.473202+00:00 [queued]>
[2023-09-21T00:53:15.596+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T00:53:10.473202+00:00 [queued]>
[2023-09-21T00:53:15.596+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T00:53:15.606+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_to_snowflake> on 2023-09-21 00:53:10.473202+00:00
[2023-09-21T00:53:15.612+0000] {standard_task_runner.py:57} INFO - Started process 900 to run task
[2023-09-21T00:53:15.615+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'send_to_snowflake', 'manual__2023-09-21T00:53:10.473202+00:00', '--job-id', '389', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpvfzvkubs']
[2023-09-21T00:53:15.617+0000] {standard_task_runner.py:85} INFO - Job 389: Subtask send_to_snowflake
[2023-09-21T00:53:15.652+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T00:53:10.473202+00:00 [running]> on host fd67d4db30a8
[2023-09-21T00:53:15.713+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='send_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T00:53:10.473202+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T00:53:10.473202+00:00'
[2023-09-21T00:53:15.715+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2023-09-21T00:53:15.715+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-09-21T00:53:15.715+0000] {connection.py:1060} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-09-21T00:53:15.715+0000] {connection.py:1068} INFO - Setting use_openssl_only mode to False
[2023-09-21T00:53:15.812+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-09-21T00:53:16.360+0000] {warnings.py:109} WARNING - /opt/***/dags/packages/student_semantic/student_semantic.py:170: UserWarning: Pandas Dataframe has non-standard index of type <class 'method'> which will not be written. Consider changing the index to pd.RangeIndex(start=0,...,step=1) or call reset_index() to keep index as column(s)
  success, num_chunks, num_rows, output = write_pandas(

[2023-09-21T00:53:16.360+0000] {cursor.py:804} INFO - query: [CREATE TEMP STAGE /* Python:snowflake.connector.pandas_tools.write_pandas() */ "...]
[2023-09-21T00:53:16.669+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T00:53:16.670+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T00:53:16.671+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 170, in send_to_snowflake
    success, num_chunks, num_rows, output = write_pandas(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/pandas_tools.py", line 295, in write_pandas
    for i, chunk in chunk_helper(df, chunk_size):
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/pandas_tools.py", line 52, in chunk_helper
    yield int(i / n), lst.iloc[i : i + n]
AttributeError: 'LazyXComAccess' object has no attribute 'iloc'
[2023-09-21T00:53:16.675+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=send_to_snowflake, execution_date=20230921T005310, start_date=20230921T005315, end_date=20230921T005316
[2023-09-21T00:53:16.688+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 389 for task send_to_snowflake ('LazyXComAccess' object has no attribute 'iloc'; 900)
[2023-09-21T00:53:16.712+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-21T00:53:16.727+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
