[2023-09-20T20:34:11.115+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T20:34:10.141504+00:00 [queued]>
[2023-09-20T20:34:11.123+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T20:34:10.141504+00:00 [queued]>
[2023-09-20T20:34:11.123+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T20:34:11.136+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_to_processed_lake> on 2023-09-20 20:34:10.141504+00:00
[2023-09-20T20:34:11.142+0000] {standard_task_runner.py:57} INFO - Started process 1976 to run task
[2023-09-20T20:34:11.146+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'send_to_processed_lake', 'manual__2023-09-20T20:34:10.141504+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpnhioi43u']
[2023-09-20T20:34:11.148+0000] {standard_task_runner.py:85} INFO - Job 206: Subtask send_to_processed_lake
[2023-09-20T20:34:11.189+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T20:34:10.141504+00:00 [running]> on host 6086152831d6
[2023-09-20T20:34:11.465+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='send_to_processed_lake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T20:34:10.141504+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T20:34:10.141504+00:00'
[2023-09-20T20:34:11.467+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 122, in send_data_to_processed
    df_processed.to_csv("data/processed/students/students.csv", index=False)
AttributeError: 'LazyXComAccess' object has no attribute 'to_csv'
[2023-09-20T20:34:11.474+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=send_to_processed_lake, execution_date=20230920T203410, start_date=20230920T203411, end_date=20230920T203411
[2023-09-20T20:34:11.485+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 206 for task send_to_processed_lake ('LazyXComAccess' object has no attribute 'to_csv'; 1976)
[2023-09-20T20:34:11.519+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T20:34:11.573+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
