[2023-09-20T19:59:42.739+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T19:59:41.955730+00:00 [queued]>
[2023-09-20T19:59:42.747+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T19:59:41.955730+00:00 [queued]>
[2023-09-20T19:59:42.748+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T19:59:42.760+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_to_processed_lake> on 2023-09-20 19:59:41.955730+00:00
[2023-09-20T19:59:42.765+0000] {standard_task_runner.py:57} INFO - Started process 1105 to run task
[2023-09-20T19:59:42.771+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'send_to_processed_lake', 'manual__2023-09-20T19:59:41.955730+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpant71p56']
[2023-09-20T19:59:42.773+0000] {standard_task_runner.py:85} INFO - Job 99: Subtask send_to_processed_lake
[2023-09-20T19:59:42.814+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T19:59:41.955730+00:00 [running]> on host 6086152831d6
[2023-09-20T19:59:43.051+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='send_to_processed_lake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T19:59:41.955730+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T19:59:41.955730+00:00'
[2023-09-20T19:59:43.063+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 87, in send_data_to_processed
    df_processed = xcom_obj[0]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 794, in __getitem__
    raise IndexError(key) from None
IndexError: 0
[2023-09-20T19:59:43.067+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=send_to_processed_lake, execution_date=20230920T195941, start_date=20230920T195942, end_date=20230920T195943
[2023-09-20T19:59:43.078+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 99 for task send_to_processed_lake (0; 1105)
[2023-09-20T19:59:43.101+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T19:59:43.114+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
