[2023-09-20T19:56:34.255+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T19:56:33.013549+00:00 [queued]>
[2023-09-20T19:56:34.263+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T19:56:33.013549+00:00 [queued]>
[2023-09-20T19:56:34.263+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T19:56:34.275+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_dataframe_student> on 2023-09-20 19:56:33.013549+00:00
[2023-09-20T19:56:34.281+0000] {standard_task_runner.py:57} INFO - Started process 1013 to run task
[2023-09-20T19:56:34.284+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'create_dataframe_student', 'manual__2023-09-20T19:56:33.013549+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpq6x1fzkl']
[2023-09-20T19:56:34.287+0000] {standard_task_runner.py:85} INFO - Job 84: Subtask create_dataframe_student
[2023-09-20T19:56:34.330+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T19:56:33.013549+00:00 [running]> on host 6086152831d6
[2023-09-20T19:56:34.899+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='create_dataframe_student' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T19:56:33.013549+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T19:56:33.013549+00:00'
[2023-09-20T19:56:34.906+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 37, in create_dataframe
    json_data = xcom_pull_obj[0]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 794, in __getitem__
    raise IndexError(key) from None
IndexError: 0
[2023-09-20T19:56:34.910+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=create_dataframe_student, execution_date=20230920T195633, start_date=20230920T195634, end_date=20230920T195634
[2023-09-20T19:56:34.922+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 84 for task create_dataframe_student (0; 1013)
[2023-09-20T19:56:34.939+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T19:56:34.951+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
