[2023-09-21T01:46:23.245+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T01:46:15.748148+00:00 [queued]>
[2023-09-21T01:46:23.251+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T01:46:15.748148+00:00 [queued]>
[2023-09-21T01:46:23.252+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T01:46:23.262+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_to_snowflake> on 2023-09-21 01:46:15.748148+00:00
[2023-09-21T01:46:23.268+0000] {standard_task_runner.py:57} INFO - Started process 2353 to run task
[2023-09-21T01:46:23.270+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'send_to_snowflake', 'manual__2023-09-21T01:46:15.748148+00:00', '--job-id', '479', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpmoopger8']
[2023-09-21T01:46:23.272+0000] {standard_task_runner.py:85} INFO - Job 479: Subtask send_to_snowflake
[2023-09-21T01:46:23.308+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T01:46:15.748148+00:00 [running]> on host fd67d4db30a8
[2023-09-21T01:46:23.368+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='send_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T01:46:15.748148+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T01:46:15.748148+00:00'
[2023-09-21T01:46:23.413+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2023-09-21T01:46:23.414+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-09-21T01:46:23.414+0000] {connection.py:1060} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-09-21T01:46:23.414+0000] {connection.py:1068} INFO - Setting use_openssl_only mode to False
[2023-09-21T01:46:23.521+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-09-21T01:46:23.996+0000] {cursor.py:804} INFO - query: [select current_database(), current_schema();]
[2023-09-21T01:46:24.313+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:46:24.314+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:46:24.316+0000] {cursor.py:804} INFO - query: [ROLLBACK]
[2023-09-21T01:46:24.614+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T01:46:24.614+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T01:46:24.615+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 198, in send_to_snowflake
    cursor = conn.cursor()
AttributeError: 'Connection' object has no attribute 'cursor'
[2023-09-21T01:46:24.620+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=send_to_snowflake, execution_date=20230921T014615, start_date=20230921T014623, end_date=20230921T014624
[2023-09-21T01:46:24.632+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 479 for task send_to_snowflake ('Connection' object has no attribute 'cursor'; 2353)
[2023-09-21T01:46:24.653+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-21T01:46:24.667+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
