[2023-09-20T20:35:12.824+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T20:35:11.575510+00:00 [queued]>
[2023-09-20T20:35:12.834+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T20:35:11.575510+00:00 [queued]>
[2023-09-20T20:35:12.835+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T20:35:12.848+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_to_processed_lake> on 2023-09-20 20:35:11.575510+00:00
[2023-09-20T20:35:12.853+0000] {standard_task_runner.py:57} INFO - Started process 2034 to run task
[2023-09-20T20:35:12.856+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'send_to_processed_lake', 'manual__2023-09-20T20:35:11.575510+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpte2ovxqf']
[2023-09-20T20:35:12.858+0000] {standard_task_runner.py:85} INFO - Job 218: Subtask send_to_processed_lake
[2023-09-20T20:35:12.904+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T20:35:11.575510+00:00 [running]> on host 6086152831d6
[2023-09-20T20:35:13.150+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='send_to_processed_lake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T20:35:11.575510+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T20:35:11.575510+00:00'
[2023-09-20T20:35:13.152+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 116, in send_data_to_processed
    df_processed.to_csv("data/processed/students/students.csv", index=False)
AttributeError: 'LazyXComAccess' object has no attribute 'to_csv'
[2023-09-20T20:35:13.159+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=send_to_processed_lake, execution_date=20230920T203511, start_date=20230920T203512, end_date=20230920T203513
[2023-09-20T20:35:13.169+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 218 for task send_to_processed_lake ('LazyXComAccess' object has no attribute 'to_csv'; 2034)
[2023-09-20T20:35:13.189+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T20:35:13.205+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
