[2023-09-21T01:16:44.851+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T01:16:36.355753+00:00 [queued]>
[2023-09-21T01:16:44.857+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T01:16:36.355753+00:00 [queued]>
[2023-09-21T01:16:44.857+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T01:16:44.867+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_to_snowflake> on 2023-09-21 01:16:36.355753+00:00
[2023-09-21T01:16:44.873+0000] {standard_task_runner.py:57} INFO - Started process 1552 to run task
[2023-09-21T01:16:44.876+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'send_to_snowflake', 'manual__2023-09-21T01:16:36.355753+00:00', '--job-id', '431', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpxcwq1npg']
[2023-09-21T01:16:44.878+0000] {standard_task_runner.py:85} INFO - Job 431: Subtask send_to_snowflake
[2023-09-21T01:16:44.914+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.send_to_snowflake manual__2023-09-21T01:16:36.355753+00:00 [running]> on host fd67d4db30a8
[2023-09-21T01:16:44.976+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='send_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T01:16:36.355753+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T01:16:36.355753+00:00'
[2023-09-21T01:16:44.978+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 159, in send_to_snowflake
    df_student.to_csv("data/processed/student_data.csv", index=False)
AttributeError: 'LazyXComAccess' object has no attribute 'to_csv'
[2023-09-21T01:16:44.985+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=send_to_snowflake, execution_date=20230921T011636, start_date=20230921T011644, end_date=20230921T011644
[2023-09-21T01:16:44.995+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 431 for task send_to_snowflake ('LazyXComAccess' object has no attribute 'to_csv'; 1552)
[2023-09-21T01:16:45.008+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-21T01:16:45.020+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
