[2023-09-20T20:34:11.085+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_missed_days manual__2023-09-20T20:34:10.141504+00:00 [queued]>
[2023-09-20T20:34:11.093+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_missed_days manual__2023-09-20T20:34:10.141504+00:00 [queued]>
[2023-09-20T20:34:11.094+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T20:34:11.104+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_dataframe_missed_days> on 2023-09-20 20:34:10.141504+00:00
[2023-09-20T20:34:11.110+0000] {standard_task_runner.py:57} INFO - Started process 1974 to run task
[2023-09-20T20:34:11.112+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'create_dataframe_missed_days', 'manual__2023-09-20T20:34:10.141504+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmp2d3me_nu']
[2023-09-20T20:34:11.115+0000] {standard_task_runner.py:85} INFO - Job 204: Subtask create_dataframe_missed_days
[2023-09-20T20:34:11.162+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.create_dataframe_missed_days manual__2023-09-20T20:34:10.141504+00:00 [running]> on host 6086152831d6
[2023-09-20T20:34:11.403+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='create_dataframe_missed_days' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T20:34:10.141504+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T20:34:10.141504+00:00'
[2023-09-20T20:34:11.414+0000] {logging_mixin.py:151} INFO - json_data []
[2023-09-20T20:34:11.414+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 76, in create_dataframe_missed_days
    df = pd.json_normalize(xcom_pull_obj[key_to_normalize], sep="_")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 789, in __getitem__
    raise ValueError("only support index access for now")
ValueError: only support index access for now
[2023-09-20T20:34:11.417+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=create_dataframe_missed_days, execution_date=20230920T203410, start_date=20230920T203411, end_date=20230920T203411
[2023-09-20T20:34:11.428+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 204 for task create_dataframe_missed_days (only support index access for now; 1974)
[2023-09-20T20:34:11.447+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T20:34:11.467+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
