[2023-09-21T06:31:41.169+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.send_to_snowflake scheduled__2023-09-20T05:00:00+00:00 [queued]>
[2023-09-21T06:31:41.181+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.send_to_snowflake scheduled__2023-09-20T05:00:00+00:00 [queued]>
[2023-09-21T06:31:41.182+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T06:31:41.196+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_to_snowflake> on 2023-09-20 05:00:00+00:00
[2023-09-21T06:31:41.201+0000] {standard_task_runner.py:57} INFO - Started process 140 to run task
[2023-09-21T06:31:41.205+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'send_to_snowflake', 'scheduled__2023-09-20T05:00:00+00:00', '--job-id', '583', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmp1qbx1vms']
[2023-09-21T06:31:41.208+0000] {standard_task_runner.py:85} INFO - Job 583: Subtask send_to_snowflake
[2023-09-21T06:31:41.255+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.send_to_snowflake scheduled__2023-09-20T05:00:00+00:00 [running]> on host fd67d4db30a8
[2023-09-21T06:31:41.335+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='send_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-20T05:00:00+00:00'
[2023-09-21T06:31:41.399+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2023-09-21T06:31:41.401+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-09-21T06:31:41.401+0000] {connection.py:1060} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-09-21T06:31:41.401+0000] {connection.py:1068} INFO - Setting use_openssl_only mode to False
[2023-09-21T06:31:41.528+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-09-21T06:31:42.411+0000] {cursor.py:804} INFO - query: [select current_database(), current_schema();]
[2023-09-21T06:31:42.666+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:42.667+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T06:31:42.670+0000] {cursor.py:804} INFO - query: [ROLLBACK]
[2023-09-21T06:31:43.039+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:43.040+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T06:31:43.040+0000] {cursor.py:804} INFO - query: [CREATE OR REPLACE TABLE student_data( student_id VARCHAR, name VARCHAR, grades_m...]
[2023-09-21T06:31:43.360+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:43.361+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T06:31:43.372+0000] {cursor.py:804} INFO - query: [DESC TABLE /* sqlalchemy:_has_object */ student_data]
[2023-09-21T06:31:43.631+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:43.632+0000] {cursor.py:959} INFO - Number of results in first chunk: 7
[2023-09-21T06:31:43.634+0000] {cursor.py:804} INFO - query: [DESC TABLE /* sqlalchemy:_has_object */ student_data]
[2023-09-21T06:31:43.863+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:43.863+0000] {cursor.py:959} INFO - Number of results in first chunk: 7
[2023-09-21T06:31:43.865+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:get_table_names */ TABLES IN student_semantic]
[2023-09-21T06:31:44.203+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:44.206+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T06:31:44.208+0000] {cursor.py:804} INFO - query: [select current_database(), current_schema();]
[2023-09-21T06:31:44.509+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:44.509+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T06:31:44.511+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:_get_schema_primary_keys */PRIMARY KEYS IN SCHEMA student_sem...]
[2023-09-21T06:31:44.813+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:44.814+0000] {cursor.py:959} INFO - Number of results in first chunk: 0
[2023-09-21T06:31:44.815+0000] {cursor.py:804} INFO - query: [SELECT /* sqlalchemy:_get_schema_columns */ ic.table_name, ic.column_name, ic.da...]
[2023-09-21T06:31:47.178+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:47.178+0000] {cursor.py:959} INFO - Number of results in first chunk: 7
[2023-09-21T06:31:47.181+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:_get_schema_foreign_keys */ IMPORTED KEYS IN SCHEMA student_s...]
[2023-09-21T06:31:47.448+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:47.449+0000] {cursor.py:959} INFO - Number of results in first chunk: 0
[2023-09-21T06:31:47.450+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:_get_schema_unique_constraints */ UNIQUE KEYS IN SCHEMA stude...]
[2023-09-21T06:31:47.677+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:47.678+0000] {cursor.py:959} INFO - Number of results in first chunk: 0
[2023-09-21T06:31:47.679+0000] {cursor.py:804} INFO - query: [SHOW /* sqlalchemy:_get_table_comment */ TABLES LIKE 'student_data']
[2023-09-21T06:31:47.989+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:47.990+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T06:31:47.992+0000] {cursor.py:804} INFO - query: [DROP TABLE student_data]
[2023-09-21T06:31:48.297+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:48.340+0000] {cursor.py:804} INFO - query: [COMMIT]
[2023-09-21T06:31:48.605+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:48.606+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T06:31:48.607+0000] {cursor.py:804} INFO - query: [ROLLBACK]
[2023-09-21T06:31:48.827+0000] {cursor.py:817} INFO - query execution done
[2023-09-21T06:31:48.827+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-09-21T06:31:48.828+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 908, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002001 (02000): 01af239e-0001-5762-0000-0002581aa185: SQL compilation error:
Object 'STUDENT_DATA' does not exist or not authorized.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 115, in send_to_snowflake
    df_student_snflk.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1910, in to_sql
    table = self.prep_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1814, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 907, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1963, in drop_table
    self.get_table(table_name, schema).drop(bind=self.con)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 979, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 1106, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 908, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 002001 (02000): 01af239e-0001-5762-0000-0002581aa185: SQL compilation error:
Object 'STUDENT_DATA' does not exist or not authorized.
[SQL: 
DROP TABLE student_data]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-09-21T06:31:48.834+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=send_to_snowflake, execution_date=20230920T050000, start_date=20230921T063141, end_date=20230921T063148
[2023-09-21T06:31:48.854+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 583 for task send_to_snowflake ((snowflake.connector.errors.ProgrammingError) 002001 (02000): 01af239e-0001-5762-0000-0002581aa185: SQL compilation error:
Object 'STUDENT_DATA' does not exist or not authorized.
[SQL: 
DROP TABLE student_data]
(Background on this error at: https://sqlalche.me/e/14/f405); 140)
[2023-09-21T06:31:48.869+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-21T06:31:48.897+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
