[2023-09-20T16:53:26.027+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_missed_days manual__2023-09-20T16:53:25.048145+00:00 [queued]>
[2023-09-20T16:53:26.035+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_missed_days manual__2023-09-20T16:53:25.048145+00:00 [queued]>
[2023-09-20T16:53:26.035+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T16:53:26.045+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_dataframe_missed_days> on 2023-09-20 16:53:25.048145+00:00
[2023-09-20T16:53:26.050+0000] {standard_task_runner.py:57} INFO - Started process 853 to run task
[2023-09-20T16:53:26.053+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'create_dataframe_missed_days', 'manual__2023-09-20T16:53:25.048145+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpq3qyo8lx']
[2023-09-20T16:53:26.056+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask create_dataframe_missed_days
[2023-09-20T16:53:26.096+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.create_dataframe_missed_days manual__2023-09-20T16:53:25.048145+00:00 [running]> on host 64864ba3aa5a
[2023-09-20T16:53:26.405+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='create_dataframe_missed_days' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T16:53:25.048145+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T16:53:25.048145+00:00'
[2023-09-20T16:53:26.406+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 20, in create_dataframe
    return pd.json_normalize(json_data[key_to_normalize], sep="_").to_csv(
TypeError: string indices must be integers
[2023-09-20T16:53:26.415+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=create_dataframe_missed_days, execution_date=20230920T165325, start_date=20230920T165326, end_date=20230920T165326
[2023-09-20T16:53:26.428+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 34 for task create_dataframe_missed_days (string indices must be integers; 853)
[2023-09-20T16:53:26.467+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T16:53:26.490+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
