[2023-09-20T20:27:53.614+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T20:27:52.241650+00:00 [queued]>
[2023-09-20T20:27:53.622+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T20:27:52.241650+00:00 [queued]>
[2023-09-20T20:27:53.622+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T20:27:53.633+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_to_processed_lake> on 2023-09-20 20:27:52.241650+00:00
[2023-09-20T20:27:53.637+0000] {standard_task_runner.py:57} INFO - Started process 1804 to run task
[2023-09-20T20:27:53.642+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'send_to_processed_lake', 'manual__2023-09-20T20:27:52.241650+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpzik9f5i9']
[2023-09-20T20:27:53.645+0000] {standard_task_runner.py:85} INFO - Job 180: Subtask send_to_processed_lake
[2023-09-20T20:27:53.686+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.send_to_processed_lake manual__2023-09-20T20:27:52.241650+00:00 [running]> on host 6086152831d6
[2023-09-20T20:27:53.954+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='send_to_processed_lake' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T20:27:52.241650+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T20:27:52.241650+00:00'
[2023-09-20T20:27:53.967+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 120, in send_data_to_processed
    df_processed.to_csv("data/processed/students/students.csv", index=False)
AttributeError: 'NoneType' object has no attribute 'to_csv'
[2023-09-20T20:27:53.973+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=send_to_processed_lake, execution_date=20230920T202752, start_date=20230920T202753, end_date=20230920T202753
[2023-09-20T20:27:53.983+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 180 for task send_to_processed_lake ('NoneType' object has no attribute 'to_csv'; 1804)
[2023-09-20T20:27:54.014+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T20:27:54.026+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
