[2023-09-20T19:28:55.259+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T19:28:54.219820+00:00 [queued]>
[2023-09-20T19:28:55.266+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T19:28:54.219820+00:00 [queued]>
[2023-09-20T19:28:55.267+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T19:28:55.279+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_dataframe_student> on 2023-09-20 19:28:54.219820+00:00
[2023-09-20T19:28:55.283+0000] {standard_task_runner.py:57} INFO - Started process 414 to run task
[2023-09-20T19:28:55.289+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'create_dataframe_student', 'manual__2023-09-20T19:28:54.219820+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpnaw0s5zr']
[2023-09-20T19:28:55.291+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask create_dataframe_student
[2023-09-20T19:28:55.330+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T19:28:54.219820+00:00 [running]> on host 6086152831d6
[2023-09-20T19:28:55.569+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='create_dataframe_student' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T19:28:54.219820+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T19:28:54.219820+00:00'
[2023-09-20T19:28:55.570+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: create_dataframe() missing 1 required positional argument: 'task_id'
[2023-09-20T19:28:55.577+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=create_dataframe_student, execution_date=20230920T192854, start_date=20230920T192855, end_date=20230920T192855
[2023-09-20T19:28:55.588+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task create_dataframe_student (create_dataframe() missing 1 required positional argument: 'task_id'; 414)
[2023-09-20T19:28:55.620+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T19:28:55.657+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
